### ISSUE TITLE
Please release version for Wicket 7

### ISSUE THREAD

**Issue by PhantomYdn** [ivaynberg/wicket-select2#108]
Otherwise there is exception:

```java
java.lang.NoSuchMethodError: org.apache.wicket.Application.setMetaData(Lorg/apache/wicket/MetaDataKey;Ljava/lang/Object;)V
	at com.vaynberg.wicket.select2.ApplicationSettings.get(ApplicationSettings.java:140)
	at com.vaynberg.wicket.select2.Select2ResourcesBehavior.renderHead(Select2ResourcesBehavior.java:35)
	at org.apache.wicket.Component.internalRenderHead(Component.java:2726)
```

**Comment by paulbors** [comment]
Feel free to create a pull request

**Comment by PhantomYdn** [comment]
This stuff already migrated to wicketstuff. And that version doesn't have this problem.

**Comment by ceefour** [comment]
Thanks :+1:
